# Generated by Django 3.2.5 on 2021-09-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Gratitude', 'Gratitude'), ('Question', 'Question'), ('Personal', 'Personal')], default=('Personal', 'Personal'), max_length=20),
        ),
    ]
