# Generated by Django 3.2.5 on 2021-09-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_alter_mood_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(choices=[('Very Negative', '0'), ('Negative', '1'), ('Neutral', '2'), ('Positive', '3'), ('Very Positive', '4')], max_length=50),
        ),
    ]
